version: "2.4"
services: 
    mongo:
        image: mongo
        volumes: 
            - ./data/db/mongo:/data/db
        ports:
            - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
        container_name: mongo_benchmark
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        volumes: 
            - ./data/db/postgres:/var/lib/postgresql/data
            - ./config:/etc/postgresql
            - ./generated:/etc/generated
        ports:
            - '5432:5432'
        container_name: postgres_benchmark
        command: postgres -c config_file=/etc/postgresql/postgres.conf
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 30s
            retries: 10
